### ISSUE TITLE
Bump release version 1.6

### ISSUE THREAD

**Issue by 3r1co** [kubernetes-sigs/aws-fsx-csi-driver#310]
Hello,
we recently upgraded our FSX CSI driver chart from 1.5.0 to 1.5.1 and noticed that there were quite significant changes included.
Among others, the Lustre client version was upgraded from 2.10 to 2.12.
Unfortunately, this Lustre client has a strong Kernel version requirement as mentioned here: https://docs.aws.amazon.com/fsx/latest/LustreGuide/install-lustre-client.html 
It created a little frustration for us, as the problem was not really evident and took some researching. We initially thought this would be an easy upgrade as only the patch version changed.

/feature

**Describe the solution you'd like in detail**
It would have been great to bump the release version for 1.6.0 to signify that there are changes that require further attention. In addition to that, the Lustre client upgrade was not mentioned in the changelog.

**Comment by jacobwolfaws** [comment]
Hi @3r1co,
Looking at the commit history, this pull request https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/293 happened after we released v0.9.0, and since the helm chart is pointing at v0.9.0, I'm not sure why the image you're using would be using the 2.12 lustre client. We're planning on releasing helm 1.6 with the next major csi driver release, which will include the transition from the 2.10 client to the 2.12 client. Can you share what you found that showed you're using an image with the 2.12 client?

**Comment by 3r1co** [comment]
Hi @jacobwolfaws ,
indeed it seems correlation was not causation here. I took my information from this release comparison: https://github.com/kubernetes-sigs/aws-fsx-csi-driver/compare/helm-chart-aws-fsx-csi-driver-1.5.0...helm-chart-aws-fsx-csi-driver-1.5.1 , in which you can see the change for the Lustre version. My assumption was that the driver image version wasn't changed however (which was weird by itself).
Indeed, I can confirm that the driver version in the 0.9.0 image remains 2.10.8-6.amzn2 .
I'll have to dig further on my side to see why I have issues with the 1.5.1 helm chart.
Thanks for reacting so quickly!

**Comment by jacobwolfaws** [comment]
Happy to help, please let me know what you find! I'll leave this issue open for a little bit in case there's a meaningful helm change we need to make with 1.6.0. Thanks!

**Comment by jacobwolfaws** [comment]
Closing this issue, @3r1co please open a new issue if you've identified an issue with the csi driver/helm chart or you've collected logs that need closer examination. 
/close
