### ISSUE TITLE
Requesting support for EKS Pod Identity

### ISSUE THREAD

**Issue by git4example** [kubernetes-sigs/aws-fsx-csi-driver#372]
**Is your feature request related to a problem?/Why is this needed**

/feature

**Describe the solution you'd like in detail**
Currently FSX CSI Driver on EKS cluster (tested on 1.29 using master branch v1.1.0) is not supporting Pod Identity (https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html)

It fails with error 
```
>
E0208 06:12:08.238251       1 driver.go:104] "GRPC error" err=<
        rpc error: code = Internal desc = Could not create volume "pvc-1c046e87-ba4f-40e1-af52-44d138ce0d50": CreateFileSystem failed: NoCredentialProviders: no valid providers in chain
        caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
        SharedCredsLoad: failed to load profile, .
        CredentialsEndpointError: invalid endpoint host, "169.254.170.23", only loopback hosts are allowed.
```

**Describe alternatives you've considered**

Had to use IRSA. 

**Additional context**

**Comment by jacobwolfaws** [comment]
From my understanding, this is purely due to the aws-sdk-go version being used in the v1.1.0 driver. Here's a PR with some more info: https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/371. We plan to release v1.2.0 by the end of this week, after which you should be able to use pod identity as expected. Will close this issue once v1.2.0 is released
